### ISSUE TITLE
When using with `@nomiclabs/hardhat-vyper`, resulting factories from vyper sources do not have correct ContractInterface type

### ISSUE THREAD

**Issue by penandlim** [dethcrypto/TypeChain#677]
Can be replicated with below repo.

https://github.com/penandlim/TestVyperPlugins

After successfully generating types, there are typescript errors in `build/typechain/factories/HelloVyper.vy/HelloVyper__factory.ts`.
Due to this type error, running test task results in errors.

```
npm ci
npx hardhat compile --no-typechain && npx hardhat typechain
npx hardhat test
```

Looks like gas properties inside the abis are set to `number` but `ContractInterface` expects it to be `string` 

I've found this issue from last year on hardhat side but dont seem like much was done at the time.

https://github.com/NomicFoundation/hardhat/issues/1696

**Comment by frontier159** [comment]
Stumbled upon this same issue, and for now manually updated the typechain *__factory.ts files such that:
```
const _abiNoGas = _abi.map( (element) => {
  const {["gas"]: _, ...withoutGas } = element;
  return withoutGas;
});
```
And set to use _abiNoGas instead of _abi.

It fixes two issues:
1. typescript complaints that the gas field isn't a string
2. The auto-generated gas estimation was incorrect - so hardhat/ethers complained unless `{gasLimit}` was manuall set on each contract function call

**Comment by frontier159** [comment]
@krzkaczor thoughts on a proposed solution? https://github.com/dethcrypto/TypeChain/pull/711

**Comment by frontier159** [comment]
This can be closed now: https://github.com/NomicFoundation/hardhat/pull/2879
