### ISSUE TITLE
Typechain 8.1.x no longer generates types for ethers-v5-target

### ISSUE THREAD

**Issue by raymondfeng** [dethcrypto/TypeChain#722]
We use hardhat/typechain to generate TypeScript types from Solidity source code and JSON ABIs.

```js
require('@typechain/hardhat');
const path = require('path');
  typechain: {
    outDir: 'src/types',
    target: 'ethers-v5',
    externalArtifacts: [path.join(__dirname, 'src/contracts/**/*.json')],
  },
};
module.exports = config;
```

It stops working after upgrading to:

@typechain/ethers-v5 | ~10.0.0 -> ~10.1.0 |   |   |   |  
-- | -- | -- | -- | -- | --
@typechain/hardhat | ~6.0.0 -> ~6.1.0 |   |   |   |  
typechain | ~8.0.0 -> ~8.1.0

No errors are given, but `src/types` are not generated.

**Comment by krzkaczor** [comment]
@raymondfeng do you have a repository with repro?

**Comment by raymondfeng** [comment]
@krzkaczor Thank you for the prompt response. Here is a repo that can be used to reproduce the problem:

https://github.com/raymondfeng/typechain-test

If we downgrade typechain ralted dependencies, `npm run build:package` works as expected.

**Comment by krzkaczor** [comment]
@raymondfeng huge thanks for the repro. The problem is that after the update, typechain is disabled if hardhat config file is written in js. I think it might be not the best change... to quickly fix it you might add `dontOverrideCompile: false`  to your typechain config. 

@alcuadrado I think we need to have a different way of checking if a project is "typescript enabled". WDYT about checking for "typescript" dependency in root package.json instead?  But finding it might not be trivial (cwd is one option...)

**Comment by alcuadrado** [comment]
This was added so that our new plugin, a bundle of recommended plugins, could always install Typechain and not annoy js users. I moved that logic to the toolbox itself.
