### ISSUE TITLE
Unmet peer dependency `@ethersproject/bytes@^5.0.0`

### ISSUE THREAD

**Issue by pcaversaccio** [dethcrypto/TypeChain#822]
If using it via e.g. Hardhat (`npm install --save-dev typechain @typechain/hardhat @typechain/ethers-v5`) you won't need the peer dependency `@ethersproject/bytes` and the `yarn` installation will issue the following warning:

```bash
@typechain/ethers-v5@10.2.0" has unmet peer dependency "@ethersproject/bytes@^5.0.0"
```

> You can reproduce this behavior e.g. [here](https://github.com/pcaversaccio/hardhat-project-template-ts/actions/runs/4667684060/jobs/8263791566#step:7:11).

My question is whether we could get completely rid of this peer dependency or if there are some specific use cases where this is required.

**Comment by zemse** [comment]
We should be able to remove the peer dependency since it seems nothing is imported from it now. When it was [added](https://github.com/dethcrypto/TypeChain/commit/87330df3fc8f6c00253fe894b7b1bcceaafb0bb0), there were some `@ethersproject/bytes` [imports](https://github.com/dethcrypto/TypeChain/blob/87330df3fc8f6c00253fe894b7b1bcceaafb0bb0/packages/target-ethers-v5/src/codegen/index.ts#L38) in the generated types, but now they are not.

**Comment by pcaversaccio** [comment]
Right, will open a PR later today.

**Comment by pcaversaccio** [comment]
FYI `@ethersproject/bytes` got already removed some time ago https://github.com/dethcrypto/TypeChain/commit/a0fba00b4372b092982882d84d29822be14d3c40#diff-32bb5e771d2c31d2542f2f152665704ff96aac9c2977a506287d6b74a1fe3bfeL41.
